# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            BetterEveryDay
tagline:          A Blog for the ever improving developers at Mayden Academy
description:      "The secret to mastery is constant improvement"
url:              "https://bettereveryday.github.io"
baseurl:          '/'

author:
  name:           'Luke Sturgess-Durden'
  url:            https://twitter.com/lukesturg

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/bettereveryday
