# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            BlackDoc
tagline:          Black Theme for Jekyll
description:      "A two-column black theme with a scrolling sidebar. Ideal for sites requiring a master-detail layout, e.g. documentation, cheatsheets, lyrics, notes..."
url:              "https://bettereveryday.github.io"
baseurl:          '/'

author:
  name:           'Luke Sturgess-Durden'
  url:            https://twitter.com/lukesturg

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/bettereveryday
